const PlatesData = [
  {
    id: 1,
    location: "Kedarnath",
    imgsrc: "./projectimg/kedar.jpg",
    detail: "4 Nights + Food",
    price: "$ 500",
    des: "Shri Kedarnath is the eleventh Jyotirlinga, out of the twelve Jyotirlinga of India was established by Aadi Guru Shankaracharya.",
  },
  {
    id: 2,
    location: "Badrinath",
    imgsrc: "./projectimg/badrinath.jpg",
    detail: "3 Nights + Food",
    price: "$ 400",
    des: "Badrinarayana Temple is a Hindu temple dedicated to Vishnu which is situated in the town of Badrinath in Uttarakhand, India. The temple is also one of the 108 Divya Desams dedicated to Vishnu.",
  },
  {
    id: 3,
    location: "Harshil",
    imgsrc: "./projectimg/harshil.jpg",
    detail: "5 Nights + Food",
    price: "$ 400",
    des: "Harsil is an unspoiled and hidden jewel of Uttarakhand state offering ample scope for people seeking peace and serenity in the lap of Himalayas.",
  },
  {
    id: 4,
    location: "Kannatal",
    imgsrc: "./projectimg/kannatal.jpg",
    detail: "3 Nights + Food",
    price: "$ 400",
    des: "Kanatal is a small village and a hill station in the state of Uttarakhand, India. Kanatal is 78 km from Dehradun, 38 km from Mussoorie and 12 km from Chamba.",
  },
  {
    id: 5,
    location: "Kedarkantha",
    imgsrc: "./projectimg/kedarkantha.jpg",
    detail: "6 Nights + Food",
    price: "$ 400",
    des: "Kedarkantha is a mountain peak of the Himalayas in Uttarakhand, India. Its elevation is 12,500 ft. Kedarkantha is located within Govind Wildlife Sanctuary in Uttarkashi district.",
  },
  {
    id: 6,
    location: "Maldevta",
    imgsrc: "./projectimg/maldevta.jpg",
    detail: "2 Nights + Food",
    price: "$ 200",
    des: "Maldevta is a safe haven for the nature lovers and adventure bugs. The virgin trails around this place lure the wanderers to trek and explore the tiny hamlets outlining the area.",
  },
  {
    id: 7,
    location: "Mussorie",
    imgsrc: "./projectimg/mussoorie.png",
    detail: "3 Nights + Food",
    price: "$ 400",
    des: "Mussoorie is a hill station and a municipal board in the Dehradun district of the Indian state of Uttarakhand. It is about 35 kilometres from the state capital of Dehradun.",
  },
  {
    id: 8,
    location: "Nainital",
    imgsrc: "./projectimg/Nainital.jpg",
    detail: "5 Nights + Food",
    price: "$ 600",
    des: "Formerly a British hill station, it’s set around Nainital Lake, a popular boating site with Naina Devi Hindu Temple on its north shore. ",
  },
  {
    id: 9,
    location: "Roopkund",
    imgsrc: "./projectimg/Roopkund.jpg",
    detail: "7 Nights + Food",
    price: "$ 700",
    des: "Roopkund is a high altitude glacial lake in the Uttarakhand state of India. The area around the lake is uninhabited and is roughly at an altitude of 5,020 metres",
  },
  {
    id: 10,
    location: "Sahastratal",
    imgsrc: "./projectimg/sahastratal.jpg",
    detail: "8 Nights + Food",
    price: "$ 900",
    des: "Tucked away in the midst of the gorgeous Garhwal Himalayas, the Sahastra Tal is located on the western end of the snow-clad Khatling glacier.",
  },
  {
    id: 11,
    location: "Tehri Lake",
    imgsrc: "./projectimg/Tehrilake.png",
    detail: "4 Nights + Food",
    price: "$ 400",
    des: "Tehri Lake where travellers can enjoy water sports such as boating, banana rides, jet skiing, surfing, paragliding, canoeing and river rafting.",
  },
];
export default PlatesData;
